plank:
  default_decoration_configs:
    "*":
      utility_images:
        clonerefs: "gcr.io/k8s-prow/clonerefs:v20200615-5d59425fc2"
        initupload: "gcr.io/k8s-prow/initupload:v20200615-5d59425fc2"
        entrypoint: "gcr.io/k8s-prow/entrypoint:v20200615-5d59425fc2"
        sidecar: "gcr.io/k8s-prow/sidecar:v20200615-5d59425fc2"
      gcs_configuration:
        bucket: aicoe-thoth-prow-artifacts
        path_strategy: explicit
      gcs_credentials_secret: gcs-credentials

github_reporter:
  job_types_to_report:
    - presubmit
    - postsubmit

tide:
  merge_method:
    thoth-station/srcops-testing: squash

  target_url: https://prow.thoth-station.dev/tide

  queries:
    - repos:
        - thoth-station/srcops-testing
        - thoth-station/workflow-helpers
      labels:
        - approved
        - lgtm
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - do-not-merge/invalid-owners-file
        - needs-rebase

  blocker_label: tide/merge-blocker
  squash_label: tide/merge-method-squash
  rebase_label: tide/merge-method-rebase
  merge_label: tide/merge-method-merge

  context_options:
    from-branch-protection: true
    skip-unknown-contexts: true
    orgs:
      thoth-station:
        required-contexts:
          - "thoth-ci/build-check"
          - "thoth-ci/pytest-check"
        repos:
          srcops-testing:
            required-contexts:
              - "thoth-ci/pytest-check"
