plank:
  default_decoration_configs:
    "*":
      utility_images:
        clonerefs: "gcr.io/k8s-prow/clonerefs:v20200615-5d59425fc2"
        initupload: "gcr.io/k8s-prow/initupload:v20200615-5d59425fc2"
        entrypoint: "gcr.io/k8s-prow/entrypoint:v20200615-5d59425fc2"
        sidecar: "gcr.io/k8s-prow/sidecar:v20200615-5d59425fc2"
      gcs_configuration:
        bucket: aicoe-thoth-prow-artifacts
        path_strategy: explicit
      gcs_credentials_secret: gcs-credentials

branch-protection:
  protect: true
  orgs:
    AICoE:
      protect: false
    aicoe-aiops:
      protect: false
    thoth-station:
      required_status_checks:
        contexts:
          - local/check
      restrictions:
        teams:
          - sourceops 
      allow_force_pushes: true

tide:
  pr_status_base_urls:
    '*': https://prow.thoth-station.dev/pr

  merge_method:
    thoth-station/srcops-testing: squash 

  target_url: https://prow.thoth-station.dev/tide

  queries:
    - repos:
        - AICoE/aicoe-ci
        - AICoE/s2i-custom-notebook
        - thoth-station/common
        - thoth-station/datasets
        - thoth-station/init-job
        - thoth-station/integration-tests
        - thoth-station/management-api
        - thoth-station/metrics-exporter
        - thoth-station/mi
        - thoth-station/report-processing
        - thoth-station/si-aggregator
        - thoth-station/si-bandit
        - thoth-station/si-cloc
        - thoth-station/slo-reporter
        - thoth-station/srcops-testing
        - thoth-station/storages
        - thoth-station/thoth-application
        - thoth-station/unresolved-package-handler
        - thoth-station/workflow-helpers
      labels:
        - approved
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/invalid-owners-file
        - do-not-merge/work-in-progress
        - needs-rebase

  blocker_label: tide/merge-blocker
  squash_label: tide/merge-method-squash
  rebase_label: tide/merge-method-rebase
  merge_label: tide/merge-method-merge

  context_options:
    from-branch-protection: true
    skip-unknown-contexts: true
    orgs:
      AICoE:
        required-contexts:
          - thoth-ci/pre-commit-check
        repos:
          s2i-custom-notebook:
            required-contexts:
              - thoth-ci/build-check
              - thoth-ci/pre-commit-check
      thoth-station:
        required-contexts:
          - thoth-ci/pre-commit-check
        repos:
          common:
            required-contexts:
              - thoth-ci/pre-commit-check
              - thoth-ci/pytest-check
          datasets:
            required-contexts:
          init-job:
            required-contexts:
              - thoth-ci/pre-commit-check
              - thoth-ci/build-check
          integration-tests:
            required-contexts:
              - thoth-ci/build-check
              - thoth-ci/pre-commit-check
              - thoth-ci/pytest-check
          management-api:
            required-contexts:
              - thoth-ci/pre-commit-check
              - thoth-ci/build-check
          srcops-testing:
            required-contexts:
              - thoth-ci/pre-commit-check
              - thoth-ci/pytest-check
          si-bandit:
            required-contexts:
              - thoth-ci/build-check
              - thoth-ci/pre-commit-check
          si-bandit:
            required-contexts:
              - thoth-ci/build-check
              - thoth-ci/pre-commit-check
          si-cloc:
            required-contexts:
              - thoth-ci/build-check
              - thoth-ci/pre-commit-check
          storages:
            required-contexts:
              - thoth-ci/pytest-check
              - thoth-ci/build-check
          unresolved-package-handler:
            required-contexts:
              - thoth-ci/build-check

presubmits:
  thoth-station/srcops-testing:
    - name: try-out-prow-plus-tekton
      agent: tekton-pipeline
      always_run: true
      rerun_command: "/run try-out-tekton"
      trigger: "(?m)^/run (all|try-out-tekton),?(\\s+|$)"
      pipeline_run_spec:
        pipelineRef:
          name: try-out-pipeline 
        resources:
        - name: git
          resourceRef:
            name: PROW_IMPLICIT_GIT_REF

periodics:
  - name: integration-tests-periodic-moc
    interval: 8h
    labels:
      preset-service-account: "true"
    spec:
      containers:
        - image: quay.io/thoth-station/integration-tests:v0.1.1
          imagePullPolicy: Always
          command:
            - "behave"
          env:
            - name: THOTH_MANAGEMENT_API_HOST
              value: management.test.thoth-station.ninja
            - name: THOTH_USER_API_HOST
              value: test.thoth-station.ninja
    annotations:
      description: Periodic integration tests on MOC
