apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: horologium
  name: horologium
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: horologium
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: horologium
    spec:
      containers:
        - args:
            - --dry-run=false
            - --config-path=/etc/config/config.yaml
          image: gcr.io/k8s-prow/horologium:v20200625-3f9f11c88f
          imagePullPolicy: IfNotPresent
          name: horologium
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/config
              name: config
              readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: horologium
      serviceAccountName: horologium
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: config
          name: config
