apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: tide
  name: tide
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: tide
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tide
    spec:
      containers:
        - args:
            - --dry-run=false
            - --config-path=/etc/config/config.yaml
            - --github-endpoint=http://ghproxy
            - --github-endpoint=https://api.github.com
            - --github-token-path=/etc/github/oauth
            - --gcs-credentials-file=/etc/gcs/service-account.json
            - --history-uri=gs://aicoe-thoth-prow-artifacts/tide-history.json
          image: gcr.io/k8s-prow/tide:v20200625-dd6a466605
          imagePullPolicy: IfNotPresent
          name: tide
          ports:
            - containerPort: 8888
              name: http
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/github
              name: oauth
              readOnly: true
            - mountPath: /etc/config
              name: config
              readOnly: true
            - mountPath: /etc/gcs
              name: gcs-credentials
              readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: tide
      serviceAccountName: tide
      terminationGracePeriodSeconds: 30
      volumes:
        - name: oauth
          secret:
            defaultMode: 420
            secretName: oauth-token
        - configMap:
            defaultMode: 420
            name: config
          name: config
        - name: gcs-credentials
          secret:
            defaultMode: 420
            secretName: gcs-credentials
